fix: slider works properly when the size changed
nhn/tui.color-picker pull request #68
Opened 2022-06-09 10:40 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Fixed an issue that did not work properly when the size of the color picker slider area was changed
* The current test doesn't give the size of the element, So I just modified it to make the existing test work correctly.

**As-Is**
![](https://user-images.githubusercontent.com/41339744/172828408-d5ca9ed9-d5c0-41bd-9bc3-48c50b868e42.gif)

**To-Be**
![](https://user-images.githubusercontent.com/41339744/172828453-0e1aff70-7fa4-4040-be82-37ec2447d13e.gif)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-06-10 07:03 UTC, lja1018 requested changes
리뷰 완료합니다.

2022-06-10 07:03 UTC, lja1018 commented on src/js/slider.js
>  Slider.prototype._moveColorSliderHandle = function(newLeft, newTop, silent) {
지금 마우스 움직일 때마다 `getClientRects`가 호출되는데 클릭 시작 시 혹은 드래그 시작 시에 1번만 호출되야할 것 같아요.

2022-06-10 07:38 UTC, adhrinae reviewed
리뷰 완료합니다. 이쪽 프로젝트는 잘 몰라도 의도는 잘 보이네요.

2022-06-10 07:38 UTC, adhrinae commented on src/js/slider.js
> +    COLORSLIDER_POS_LIMIT_RANGE[1] = sliderRects.height - 10;
기존에는 변하지 않을 값이라 생각해서 전부 대문자인 상수 변수로 처리한거같은데 이제 상황에 따라 동적으로 재할당되어야하는 상황이 되었으니 변수 네이밍 변경이 되었으면 좋겠네요. 나머지는 별 이견 없습니다.

2022-06-13 00:46 UTC, jwlee1108 reviewed
리뷰 완료합니다.

2022-06-13 00:46 UTC, jwlee1108 commented on src/js/slider.js
>  Slider.prototype._moveColorSliderHandle = function(newLeft, newTop, silent) {
이름은 슬라이더가 움직일 때마다 호출되는 함수 같은데 전체 코드상 맞는지 확인 부탁드려요.

2022-06-14 00:29 UTC, adhrinae approved these changes
LGTM

그런데 이제와서 깨달은거지만, 컬러피커가 IE8+ 지원이라고 써있는데 querySelector를 쓰고 있네요. 이미 쓰고있었던거니까 IE8 지원은 안되고있는거라고 봐야할지도...

2022-06-14 02:05 UTC, jajugoguma commented
@adhrinae 
querySelector와 같이 IE8에서 지원하지 않는 메서드 등을 제거해 IE8+를 올바르게 지원하도록 하는 작업은 별도 업무로 진행하겠습니다!

2022-06-14 02:06 UTC, merged

2022-06-14 02:18 UTC, adhrinae commented
@jajugoguma 
오히려 이건 확인 후에 IE9+으로 문서를 바꿔야하는거 아닌가 싶어요 ㅎㅎ

2022-06-14 02:22 UTC, jajugoguma commented
@adhrinae 
아 그러면 랩장님도 포함해서 회의를 한 번 해야겠군요... ㅜㅜ